name: "Update base-files package info"
# Trigger this in a train (from generate-jira-excerpt.yml)
on:
  workflow_dispatch:
  repository_dispatch:
    types: ["Base files"]

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      # Step 3: Install dependencies (if you have any)
      - name: Install dependencies
        run: |
          sudo apt install -y python3-requests python3-lxml
      # Step 4: Run the Python script
      - name: Run parser script
        run: |
          ./scripts/generate-base-files-info-json.py base-files
      # Step 5: Commit changes if any
      - name: Commit changes if any
        run: |
          git checkout data
          mkdir -p data/
          mv base-files.json data/base-files.json
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/base-files.json
          git diff --cached --quiet || git commit -m "Update base-files package info"
          git push

      - name: "Generate directory"
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: "Generate directory"

